[workspace]
resolver = "2"
members = [
    "rustodon-core",
    "rustodon-db",
    "rustodon-api",
    "rustodon-auth",
    "rustodon-activitypub",
    "rustodon-workers",
    "rustodon-search",
    "rustodon-mailer",
    "rustodon-admin",
    "rustodon-config",
    "rustodon-logging",
    "rustodon-metrics",
    "rustodon-cache",
    "rustodon-queue",
    "rustodon-storage",
    "rustodon-notifications",
    "rustodon-media",
    "rustodon-federation",
    "rustodon-webhooks",
    "rustodon-scheduler",
    "rustodon-migrations",
    "rustodon-cli",
    "rustodon-server",
    "rustodon-streaming",
    "rustodon-oauth",
    "rustodon-polls",
    "rustodon-bookmarks",
    "rustodon-reports",
    "rustodon-follow-requests",
    "rustodon-announcements",
    "rustodon-custom-emojis",
    "rustodon-trends",
    "rustodon-tags",
    "rustodon-conversations",
    "rustodon-mentions",
    "rustodon-favourites",
    "rustodon-reblogs",
    "rustodon-follows",
    "rustodon-filters",
    "rustodon-lists",
    "rustodon-groups",
    "rustodon-statuses",
    "rustodon-accounts",
    "rustodon-instances",
    "rustodon-domains",
    "rustodon-sessions",
    "rustodon-applications",
    "rustodon-access-tokens",
    "rustodon-access-grants",
    "rustodon-devices",
    "rustodon-encrypted-messages",
    "rustodon-preview-cards",
    "rustodon-scheduled-statuses",
    "rustodon-status-pins",
    "rustodon-account-notes",
    "rustodon-account-warnings",
    "rustodon-account-moderation-notes",
    "rustodon-account-deletion-requests",
    "rustodon-account-aliases",
    "rustodon-account-conversations",
    "rustodon-account-suggestions",
    "rustodon-annual-reports",
    "rustodon-terms-of-service",
    "rustodon-user-settings",
    "rustodon-web",
    "rustodon-mutes",
    "rustodon-blocks",
    "rustodon-ip-blocks",
    "rustodon-email-domain-blocks",
    "rustodon-canonical-email-blocks",
    "rustodon-appeals",
    "rustodon-bulk-imports",
    "rustodon-software-updates",
    "rustodon-severed-relationships",
    "rustodon-tag-follows",
    "rustodon-follow-recommendation-suppressions",
    "rustodon-webauthn-credentials"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["arkSong <arksong2018@gmail.com>"]
description = "A Rust implementation of Mastodon server backend, aiming for 100% compatibility with original Mastodon server functionality"
license = "AGPL-3.0"
repository = "https://github.com/arkCyber/Rustodon"
keywords = ["mastodon", "activitypub", "federation", "social-network", "rust"]
categories = ["web-programming", "api-bindings", "social-networking"]

[workspace.dependencies]
# Core async runtime
tokio = { version = "1.35", features = ["full"] }

# Web framework - using stable versions
axum = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "trace", "compression-full", "limit"] }

# Logging - simplified approach
tracing = { version = "0.1.40", features = ["std"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "local-time"] }

# Serialization
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

# Database
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }

# Error handling
thiserror = "1.0.56"
anyhow = "1.0.79"

# Utilities
uuid = { version = "1.7.0", features = ["v4", "serde"] }
chrono = { version = "0.4.31", features = ["serde"] }
bcrypt = "0.15.0"
jsonwebtoken = "9.2.0"
rand = "0.8.5"
config = "0.14.0"
clap = { version = "4.4.11", features = ["derive"] }
futures = "0.3.29"
async-trait = "0.1.77"

# Caching and storage
redis = { version = "0.24.0", features = ["tokio-comp"] }

# HTTP client
reqwest = { version = "0.11.23", features = ["json", "stream"] }

# URL and MIME handling
url = "2.5.0"
mime = "0.3.17"
mime_guess = "2.0.4"

# File system
tempfile = "3.8.1"
walkdir = "2.4.0"
glob = "0.3.1"

# Text processing
regex = "1.10.2"

# Concurrency and data structures
lazy_static = "1.4.0"
dashmap = "5.5.3"
parking_lot = "0.12.1"
crossbeam-channel = "0.5.8"
rayon = "1.8.0"

# CLI and UI
indicatif = "0.17.7"
console = "0.15.8"
colored = "2.1.0"

# Logging (fallback)
env_logger = "0.10.2"
log = "0.4.20"

# System
backtrace = "0.3.69"
num_cpus = "1.16.0"
libc = "0.2.150"
