version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: rustodon-db
    environment:
      POSTGRES_USER: rustodon
      POSTGRES_PASSWORD: rustodon
      POSTGRES_DB: rustodon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Rustodon Server
  rustodon:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: rustodon-server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rustodon:rustodon@db:5432/rustodon
      RUST_LOG: info
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
